server:
  http_port: ":8080"
  read_timeout: "5s"
  write_timeout: "10s"

database:
  master:
    host: "db"
    port: "5432"
    name: "sales_db"
    ssl_mode: "disable"

  slaves: [ ]

  max_open_connections: 10
  max_idle_connections: 5
  conn_max_lifetime: "30m"

analytics:
  percentile_default: 0.9